---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: tomcat-rc
 labels:
  author: edureka
  type: webserver
spec:
 replicas: 3
 selector:
  matchLabels:
   type: webserver
 template:
  metadata:
   name: tomcat-pod
   labels:
    type: webserver
  spec:
   containers:
    - name: mytomcat
      image: tomcat
